### ISSUE TITLE
예제 Dataset Raw Image 형태 관련 문의

### ISSUE THREAD

**Issue by mirusu400** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#1]
안녕하세요 컴퓨터정보공학부 김성진입니다.

제공된 프로젝트 과제 PDF파일과, 프로젝트 설계 PDF를 보고 문의사항이 있어 이슈 남깁니다.

https://github.com/Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1/blob/dae230147a8c72af80891709a09a8fc50106db15/Linux/rawreader.cpp#L15-L28

위 예제 소스코드를 확인해보면, 이미지 파일은 흑백으로 이루어진 RAW 파일을 대상으로 작성된 예제 소스로 보입니다.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/25397908/190949734-141082c0-51f5-4591-859f-8ddb8464f905.png">

하지만, 같이 제공된 raw 이미지 파일을 확인해보면 단순히 흑백 값만을 저장하는 것이 아닌 일반적인 `PNG`파일의 헤더를 따르고 있습니다. 첨부된 모든 파일을 확인해봤을때 모두 `raw` 형태가 아닌 `PNG`를 따르고 있었습니다.

정상적인 이미지가 첨부되었는지 확인 부탁드립니다. 만약 의도된 행동이라면, PNG를 raw로 변환하는 프로그램 또한 추가로 구현해야 하는지 문의드립니다.

**Comment by Lukious** [comment]
양식 강제변환 과정에서 헤더에 오류가 생겼던것 같습니다.

Dataset 업데이트 하였으니 확인바랍니다.

감사합니다.

**Comment by mirusu400** [comment]
빠른 반영 감사합니다.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/25397908/190958060-977d14e5-b3f2-456a-8229-2494ef25134b.png">

본 PDF에서, `(*본 프로젝트에서 사용하는 이미지 파일의
크기[Width, Height]는 고정적이며, 동일하다)` 라고 나와있는데, 첨부해주신 Raw파일들을 확인해보니 모두 `256x256(0xFFFF)`의 크기를 가지고 있습니다.

하지만 제공된 소스코드에서는 이를 `512x512` 크기를 가졌다고 가정하고 작성되어있는데, 정확한 이미지의 크기를 몇으로 설정하고 소스코드를 작성하면 되나요?

**Comment by Lukious** [comment]
256*256 이미지를 바탕으로 진행하시면 됩니다.

-2022.09.21 업데이트 

실습 수업 시간에 안내드린대로 스켈레톤코드로 작성된 raw file 읽기 코드는 단순 참고용이며, 프로젝트 자체에 그대로 사용하시면 안됩니다.
