### ISSUE TITLE
csv 파일 경로에 관한 질문

### ISSUE THREAD

**Issue by hamoci** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#10]
안녕하세요. 데이터구조실습(수), 설계를 수강중인 컴퓨터정보공학부 하준혁입니다.
구현 중 궁금증이 생겨 질문 드립니다.
csv파일을 읽어야 하는데, csv 파일의 위치가 어디에 있어야 하는지 정확하게 명시가 안되어 있습니다.
csv파일이 Project파일의 루트 디렉토리에 있어야 하는지, Image가 들어있는 img_files와 같은 파일 안에 있어야 하는지 궁금합니다.
감사합니다.

**Comment by Lukious** [comment]
Project파일의 루트 디렉토리에 위치하면 됩니다.

**Comment by hamoci** [comment]
답변 감사드립니다.

**Comment by hamoci** [comment]
제가 과제 pdf를 명확하게 읽지 않고 질문한 듯하네요. 정말 죄송합니다.
<img width="797" alt="스크린샷 2022-10-03 오전 4 35 33" src="https://user-images.githubusercontent.com/55676675/193472885-493049c2-6cf0-4afc-9eef-da70dffa1c3e.png">
과제 명시에는 루트 디렉토리가 아닌 img_files안에 있는 것으로 명시가 되어있었네요. 혹시 파일의 위치를 어디에 놓으면 좋을지 다시 한번 질문해도 괜찮을까요? 혼동을 드려서 진심으로 사과드립니다.
감사합니다.

**Comment by Lukious** [comment]
조교 논의 결과 프로젝트 루트 디렉토리와 이미지 파일 폴더 디렉토리 둘 다 허용하기로 하였습니다.

감사합니다.

**Comment by hamoci** [comment]
답변 감사합니다.
