### ISSUE TITLE
makefile 실행 오류 관련 질문

### ISSUE THREAD

**Issue by hanoong7** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#11]
안녕하세요. 2021202061 류한웅입니다.
코드를 구현하다가 터미널에서 makefile을 실행시켰는데 아래 사진과 같은 에러가 발생했습니다.
<img width="1108" alt="스크린샷 2022-09-29 오후 10 03 08" src="https://user-images.githubusercontent.com/108854591/193038856-29a6edad-5d78-49b6-9b82-9fc6ff2cc8ec.png">

구글링도 많이하고 주변 지인분들께 많은 도움도 구했지만 해결하지 못했습니다.
Vscode 설정 문제인줄 알고 Issues 탭에 질문을 올리지 않고 조교님께 메일을 드렸으며 아래와 같은 답변을 받았지만,
해결되지 않았고 Issues 탭에 질문해도 되는 문제라고 하셔서 다시 질문드립니다.
<img width="478" alt="스크린샷 2022-09-29 오후 10 04 55" src="https://user-images.githubusercontent.com/108854591/193039654-e8253692-2fe3-47e1-8b92-05bde298662b.png">

조교님의 답변을 받고 main 함수가 여려개 존재하는지 확인했고, 2개의 main 함수가 존재하는 것을 발견했습니다.
그래서 둘 다 주석처리도 해보고, 하나만 주석처리도 해봤지만 같은 에러가 발생해서 다시 질문드립니다.
답변해주시면 감사하겠습니다.

**Comment by Lukious** [comment]
코드상의 문제인것으로 보입니다. 

현재 학생이 전달해준 자료만으로는 문제를 파악할 수 없음으로 실습시간에 전체 코드와 함께 질문 부탁드리겠습니다.

**Comment by hanoong7** [comment]
안녕하세요 답변해주셔서 감사합니다.
월요일 실습 수업인데 제출기한까지 수업이 없는 것으로 알고 있습니다
​
-----Original Message-----

**Comment by Lukious** [comment]
다음주 중 새빛관으로 방문하실 수 있는 일정을 이메일로 보내주시면 감사드리겠습니다.

**Comment by hanoong7** [comment]
화요일 6시 이후만 빼면 시간표에서 수업 없는 시간은 다 괜찮습니다.
시간 내주셔서 감사합니다
​
-----Original Message-----
