### ISSUE TITLE
Loaded_list에서 선행 노드 간의 일반적인 list로 연결.

### ISSUE THREAD

**Issue by dain0127** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#12]
안녕하세요 데이터구조실습 (금)수업을 듣는 2020202007_백창인 입니다.

프로젝트 pdf에서 다음과 같은 내용이 있습니다.

Loaded_LIST의 파일 노드는 링크드 리스트 형식으로 연결되어 있어야 하며, 각각의 파일 선행 노드
(그림에서 ‘img_files’와 ‘new_files’)의 경우 일반적인 리스트 형식으로 연결되도록 한다. Loaded_LIST
에 존재하는 디렉토리에 대해 LOAD 혹은 ADD가 실행되면 기존에 Loaded_LIST에 존재하는 디렉토리
에 대한 리스트를 삭제하고 새로 리스트를 추가하는 방법으로 Loaded_LIST를 업데이트 한다. 

이때 '일반적인 리스트 형식'이라는 것이 정확히 어떤 것을 이야기 하는지 궁금합니다. array를 이용하는 것인지 아니면 STL에서 list를 이용해도 되는건지 모르겠습니다.
STL같은 경우에는 list가 이중연결리스트로 구현이 되어있으므로, 만약에 STL을 통해서 '일반적인 리스트'를 사용한다면, 파일 노드들이 연결리스트로'만' 연결이 되어야한다는 것에서 위배되지 않아 헷갈립니다.

요약하자면, '일반적인 리스트'를 사용하라는 의미가 array나 stl의 list를 사용해도 된다는 의미인지 묻고싶습니다.

**Comment by Lukious** [comment]
일반적인 리스트 형식은 C에서 array(배열)을 의미합니다.

배열로 구현해주시면 되겠습니다.

**Comment by mirusu400** [comment]
데이터구조실습 (수) 수업을 듣는 2019202074_김성진입니다.

이전에 오프라인으로 질문드렸을때는 해당 조교님이 링크드 리스트나 배열형식 아무거나 괜찮다고 답을 받았는데, 그렇다면 링크드 리스트로 해당 부분을 구현했다면 다시 배열 형식으로 구현해야하나요?

Related: #6

**Comment by Lukious** [comment]
@mirusu400 해당 조교님께 여쭤본 결과 질문을 잘못 이해하셨다고 합니다. 구현은 가능한 array(배열) 형식으로 부탁드리겠습니다.

**Comment by mirusu400** [comment]
답변 감사합니다!

**Comment by mirusu400** [comment]
@Lukious 현재 데이터구조설계(수) 수업에서 오프라인으로 물어본 답으로는, `파일 선행 노드에 대해서 링크드 리스트로 구현해야 한다` 라고 답을 받은 상태인데, 해당 질문과의 답이 서로 다른것 같습니다. 혹시 배열로 구현해야하는것이 맞는지 다시한번 여쭤봐도 될까요? 조교분들에 따라서 답이 달라 혼란을 겪고 있습니다.

**Comment by Lukious** [comment]
@mirusu400 

우선적으로 디렉토리 노드 **간** 의 연결은 일반 배열로 구현된다는점 명확히 알려드립니다. 

'파일 선행 노드'라는 질문이 모호해서 그런것 같습니다. '파일명을 연결하는 노드 그룹'은 선행노드가 링크드리스트 입니다. 하지만 구조를 전체 데이터구조로 가정하고 물어본다면 '디렉토리 정보 노드와 파일명을 연결하는 노드'간의 선행노드는 링트드리스트 연결이 맞습니다. 

<img width="480" alt="image" src="https://user-images.githubusercontent.com/25575989/194010407-612becc1-e5a2-4312-899a-8ef74d584308.png">

**이미지와 함께 설명을 드리면 이미지에서 굵은 검정선은 일반적인 배열로 연결, 회색선은 링크드리스트 연결입니다.**

정리하자면 질문의 혼선이 생기는 부분은 [디렉토리 정보 노드와 첫번째 파일명,디렉토리,번호 노드의 연결이 어떤 방식인지 물어보는것인지](선행노드를 첫번째 파일명,디렉토리,번호 노드로 가정), [디렉토리 노드 간의 연결을 물어보는것인지](선행노드를 디렉토리 노드로 가정)에 관한 내용인것 같으며 위의 bold된 단락을 참고하시어 구현하시면 될것 같습니다.

**Comment by mirusu400** [comment]
답변 감사합니다!
