### ISSUE TITLE
SELECT와 EDIT 명령어에 대한 질문

### ISSUE THREAD

**Issue by 283kr** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#13]
안녕하십니까. 데이터구조실습(금), 설계를 수강중인 2019610005 이방산입니다.
문제 이해 중에 헷갈리는 것이 있어 질문 드립니다.

1. SELECT 명령어 입력 후 SUCCESS를 출력하고 동시에 이미지를 프로그램 상에 저장하는 것입니까?
2. 그렇다면 SELECT 명령어가 2번 수행되면 처음 SELECT 명령어에 명시된 이미지는 비워주고 마지막으로 저장된 이미지만 남기면 되는 것인가요?
3. SELECT 명령어가 입력되지 않은 상태에서 EDIT 명령어가 입력되면 에러를 출력하면 되는건가요?
4. 다음은 프로젝트 스펙 PDF의 일부분 입니다.
![image](https://user-images.githubusercontent.com/96465588/193286878-f9da6011-9c04-4d31-9841-b1bf0628d852.png)
![image](https://user-images.githubusercontent.com/96465588/193287104-1e8313c4-544f-45ed-8001-db4da2ac829f.png)
1번 질문과 비슷한데, 이미지를 불러오는 과정을 수행해야 하는 명령어는 SELECT입니까? 아니면 EDIT 입니까?

읽어주셔서 감사합니다!

**Comment by Lukious** [comment]
1. 네 맞습니다.
2. 네 맞습니다. 일반적인 덮어 쓰기와 동일하게 동작하면 되겠습니다.
3. 네 맞습니다.
4. SELECT입니다. EDIT은 불러온 이미지를 수정할때 (연산될때) 사용됩니다.

**Comment by 283kr** [comment]
답변해주셔서 감사합니다!
