### ISSUE TITLE
출력형태 관련 질문입니다.

### ISSUE THREAD

**Issue by gasungfa** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#14]
안녕하세요 2019202075김효석입니다. 1가지 질문 드릴게 있어서 issue작성합니다
1. 출력할때 skeleton code에 있는 대로 log.txt에 결과값을 출력하면 될까요?

**Comment by Lukious** [comment]
네 log.txt 파일에 로그를 출력해주시면 됩니다.
