### ISSUE TITLE
파일 선행 노드 연결시 벡터 사용 질문

### ISSUE THREAD

**Issue by hanoong7** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#15]
안녕하세요 2021202061 류한웅입니다.
파일 선행 노드를 연결할 때 일반 배열을 사용하라고 하셨는데,
가변 배열인 vector를 사용해도 문제가 없을지 질문드립니다.
감사합니다.

**Comment by jw03070** [comment]
일반 배열과 vector를 사용한 가변 배열 모두 가능합니다.
감사합니다.
