### ISSUE TITLE
EDIT 명령어, 컴파일, 파일 이름 관련 질문

### ISSUE THREAD

**Issue by hamoci** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#16]
안녕하세요. 데이터구조실습(수), 데이터구조설계를 수강중인 하준혁입니다.
EDIT 명령어를 구현하는 중, 궁금한 점이 생겨 질문 드립니다.

(1) SELECT 명령어로 BST에 저장된 BST_Node를 선택하여 EDIT -f를 통해 점대칭을 한 뒤에 그 직후 다시 EDIT -l 50을 하면 점대칭이 된 이미지를 밝게 만들어야 하나요? 아니면 점대칭이 되지 않은 원본 파일의 밝기를 조절하여 다시 덮어쓰기를 하나요?
(2) 컴파일 에러때문에 컴파일이 아예 안되는 경우가 아니라, 컴파일은 정상적으로 이루어지지만 warning이 발생하는 (ex.암시적 형변환 등) 경우는 감점인가요?
(3) Raw file이나 폴더 이름은 모두 소문자로 고정되어있나요(Result 폴더 제외하고)? 그렇지 않다면 Search나 Modify 명령어를 사용할 때 소문자, 대문자가 모두 섞여있어도 이름이 동일하다면 동작을 수행해야 하는지 궁금합니다.

감사합니다.

**Comment by jw03070** [comment]
(1) EDIT 명령어의 경우 하나의 이미지에만 적용하시면 됩니다. 하나의 이미지에 두번의 EDIT을 할 경우는 생각 안하셔도 무방합니다.
(2) Warning의 경우는 감점이 없습니다.
(3) Raw file이나 폴더 이름은 모두 소문자로 고정되어 있다고 생각하시면 됩니다.

**Comment by hamoci** [comment]
빠른 답변 정말 감사드립니다.
