### ISSUE TITLE
프로그램 에러 처리 관련 질문

### ISSUE THREAD

**Issue by mirusu400** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#17]
안녕하세요. 데이터구조실습(수)를 수강중인 김성진입니다.

프로그램 에러 처리에 대한 의문이 있어 이에 문의하고자 이슈를 남깁니다.

* 오류 발생시, 오류에 해당되는 오류코드를 출력하고 프로그램을 종료해야되나요? 아니면, 해당 명령어를 넘어가고 다음 명령어를 진행해야 하나요?
* `Requirements in implementation` 에서 하단과 같은 명세가 나와있는데, 이 경우 `잘못된 명령어(777)` 에러코드를 출력해야 하는지 혹은 해당 명령에 해당하는 에러코드를 출력해야하는지 궁금합니다.
 > 명령어에 인자(Parameter)가 모자라거나 필요 이상으로 입력 받을 경우 에러 코드를 출력한다

**Comment by jw03070** [comment]
(1)EXIT 명령어가 있기 때문에 오류 발생시 오류코드를 출력하고 다음 명령어를 진행하도록 하시면 됩니다.
(2)잘된 명령어 에러코드 777로 출력하는게 맞습니다. 다만 인자를 잘못 받은 명령어의 에러코드를 출력하여도 감점은 없습니다.
