### ISSUE TITLE
BST에 관한 질문

### ISSUE THREAD

**Issue by minckwon** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#18]
안녕하세요 데이터 구조 실습 수요일을 수강중인 2019202018 권민철입니다.
각파일 디렉토리 별로 100개 가 아닌 모든 디렉토리의 노드들의 갯수가 100개가 넘으면 안되는 것으로 넘으면 제일 위의 mainnode가 가리키는 첫번째 file node를 삭제하도록 어제 데이터 구조설계 수업 zoom에서 들었습니다. 따라서 MOVE를 진행할때 100개가 넘지 않았음을 이해하였고, MOVE또한 여러번 가능하다는 것을 이해하였습니다.

MOVE는 기본적으로 LOAD가 된 상황에서 상황에따라 ADD가 진행이 된 상태의 node들을 BST로 옮겨주게 되는데, MOVE를 여러번 실행시켰을때 ADD된 파일들은 다 다를 수 있지만, LOAD는 기본적으로 동일합니다. 그러면 LOAD들은 겹쳐지니 ADD된 파일들만 새로 추가를 해주면 되는건가요?

그리고 만약
LOAD
MOVE
 LOAD
ADD 
MODIFY (LOAD에 해당된 파일 고유번호 변경)
이렇게 진행하는경우에는
같은 이름의 파일에 대해 고유번호가 다르게 두개의 노드가 존재하지 않나요?

어제 LOAD를 여러번 하는 이유에 대해 수업시간에 여쭈어보니, LOAD되는 기본 데이터를 MODIFY할 경우를 위해 LOAD를 여러번 할 수 있다라고 말씀해주셔서 LOAD에 해당하는 파일의 번호를 변경하기 위함인 것 같습니다.

이렇게 MOVE를 진행하게되면 SEARCH를 구현할때 같은 이름에 해당하는 두개의 번호가 다른 NODE가 존재하는 것인데 이는 file validation처리를 해야하나요?

**Comment by jw03070** [comment]
그러면 LOAD들은 겹쳐지니 ADD된 파일들만 새로 추가를 해주면 되는건가요?
A: 예 맞습니다.
같은 이름의 파일에 대해 고유번호가 다르게 두개의 노드가 존재하지 않나요?
A: 그런 경우는 존재하지 않는다 가정하고 진행해주시면 됩니다. 

특정 상황에서 예외처리에 대해 걱정이 많으신듯 합니다.
하지만 이번 프로젝트는 예외처리에 초점이 가있기 보다는 명령어 구현에 초점이 가있는 프로젝트 입니다.
특수한 상황에 동작하지 않을수 있지만 모든 경우의 수를 다 예외처리 하실 필요는 없습니다. 
감사합니다.
