### ISSUE TITLE
STL 사용 문의

### ISSUE THREAD

**Issue by lmmh202** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#19]
안녕하세요 2021202071 이민형입니다.
프로젝트 구현 중에 궁금한 점이 생겨서 질문 드립니다.
먼저, Search 명령어에서 Queue를 사용하는데 STL에 존재하는 Queue를 사용해도 되는지 궁금합니다.
또한 Loaded_List에 Insert할때 파일 명을 대문자로 저장해야 되는지 궁금합니다.

읽어주셔서 감사합니다.

**Comment by jw03070** [comment]
(1) 핵심 알고리즘은 최대한 STL을 배제하고 구현 부탁드립니다.
(2) 굳이 대문자로 변경하여 저장 하실 필요는 없습니다.
