### ISSUE TITLE
스켈레톤 코드 활용 관련 문의

### ISSUE THREAD

**Issue by bbang-jun** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#2]
안녕하세요.

데이터구조실습(수) & 데이터구조설계를 수강하는 컴퓨터정보공학부 강병준입니다.

레포지토리에 올라와 있는 스켈레톤 코드 관련 문의가 있어 이슈를 남깁니다.

데이터구조설계 수업 이후 교수님께 따로 스켈레톤 코드 사용 여부에 대해 여쭤보았는데, 깃허브의 스켈레톤 코드를 그대로 

사용하여 구현을 하도록 말씀해주셨습니다. 

그런데 깃허브 첫 번째 이슈에

**"실습 수업 시간에 안내드린대로 스켈레톤코드로 작성된 코드는 단순 참고용이며, 프로젝트 자체에 그대로 사용하시면 안됩니다."**
 
라고 comment에 쓰여 있어서 어떻게 해야할 지 여쭤보고 싶습니다.

또한, 스켈레톤 코드를 그대로 사용하지 않고 변형하여 사용할 수 있다면 템플릿 대신 링크드 리스트(타입 고정)를 통한 구현을 해도 

가능한지에 대한 여부가 궁금합니다.

감사합니다.

**Comment by Lukious** [comment]
스켈레톤 코드는 변형 가능하며 교수님께서 말씀하신 취지는 너무 많은 변형으로 인해 스파게티 코드가 되는것을 방지하고자 하신 말씀인 것으로 생각됩니다.

스켈레톤 코드의 변형은 자유이며 인자의 삭제/추가 함수나 클래스의 추가 선언도 모두 자유임을 알려드립니다.
(다만 보고서에 이에대한 사유도 기술해 주시면 평가하기 더욱 수월할 것으로 생각됩니다.)

또한 

"실습 수업 시간에 안내드린대로 스켈레톤코드로 작성된 코드는 단순 참고용이며, 프로젝트 자체에 그대로 사용하시면 안됩니다."

라는 구문은 raw파일을 읽는 해당 파일에 한정된 이야기이며, 이외 코드는 모두 자율적으로 작성하시면 됩니다.

감사합니다.
