### ISSUE TITLE
Linked List 선행 노드 & SEARCH 단어 질문

### ISSUE THREAD

**Issue by SOM916** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#20]
안녕하세요 저는 데이터구조실습 금요일(5,6교시)를 듣는 2021202066 임소미라고 합니다. 메일로 질문을 보냈지만 issue로 올라온 질문만 회의를 진행한다고 하셔서 이렇게 다시 올립니다.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/97082128/194267558-d3816c9d-75bb-400b-a69f-2ba2cae2317b.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/97082128/194267686-cae2f609-936f-453e-9f49-00876c48c8ff.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/97082128/194267814-8a974c48-8da0-42ff-9e05-a7461163d28e.png">

(1) Linked List를 생성하는 부분 중 "Loaded_LIST의 파일 노드는 링크드 리스트 형식으로 연결되어 있어야 하며 각각의 파일 선행 노드의 경우 일반적인 리스트 형식으로 연결되도록 한다."라고 적혀있습니다. 위의 사진처럼 조교님들마다 말이 다르고 10월 5일 데이터구조설계 수업에서도 수업 중 조교님이 링크드 리스트 형식으로 구현이 허용된다고 말씀하셨습니다.  

github에 올려진 "Loaded_list에서 선행 노드 간의 일반적인 list로 연결"이라는 제목의 질문으로 결론적으로는 파일의 선행노드는 배열으로만 구현해야한다라고 이해했습니다. 

**저 같은 경우 배열로 구현했다가 링크드 리스트 형식으로도 가능하다고 하여서 링크드 리스트로 다시 구현을 했는데요 혹시 이 부분에 대해서 링크드 리스트형식과 배열 형식 둘 다 허용되어 채점하게 되는 가능성은 없을까요??**

<img width="383" alt="image" src="https://user-images.githubusercontent.com/97082128/194272396-eebd2882-c11e-460a-ad8d-46b07cec02a9.png">

<img width="314" alt="image" src="https://user-images.githubusercontent.com/97082128/194268065-bfc73b3b-793d-4362-a584-d57c5477225d.png">

(2)**SELECT 명령어를 실행 시킬 때 다음과 같이 man을 값으로 전달해줬을 때  woman같이 man을 포함한 단어 모두 출력해야하는 건지 아니면 man단어만 출력해야하는건지 궁금합니다.**

읽어주셔서 감사합니다

**Comment by bbang-jun** [comment]
수업 시간에 교수님께서는 링크드 리스트로 구현하라는 말씀을 해주셨습니다. 
배열 구현 방식, 링크드 리스트 구현 방식 모두 구현 방식에 대한 감점 요소가 없도록 해주시면 감사하겠습니다.

**Comment by Lukious** [comment]
배열 구현 방식, 링크드 리스트 구현 방식 모두 구현 방식 모두 허용하는것으로 변경하도록 하겠습니다. 

해당 이슈는 원 출제 조교와 다른 조교 간 의사소통 문제로 인해 발생한 문제였으며, 
학생들이 혼란스러움을 겪을 수 있다는 점 등을 바탕으로 프로젝트 수정 회의를 진행하였습니다.

이슈 보고 감사드리며 이슈 처리과정에서 혼란을 드린점 죄송합니다.

감사합니다.

**Comment by Lukious** [comment]
(2)번 질문은 포함한 단어 모두를 출력해 주시면 됩니다. (기본 패턴 탐색 알고리즘과 동일하게)

**Comment by SOM916** [comment]
답변 감사합니다
