### ISSUE TITLE
image 파일 위치 관련 질문

### ISSUE THREAD

**Issue by 2h1082** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#21]
안녕하세요. 데이터구조실습(수),설계를 수강 중인 컴퓨터정보공학부 이홍일입니다.
프로젝트 진행 중 궁금한 점이 있어 질문 드립니다.
git에서 프로젝트 스켈레톤 코드를 다운받으면 아래 사진과 같이 폴더들이 존재합니다.
![image](https://user-images.githubusercontent.com/95967939/194594636-256c1bfa-f662-4e1b-a9a4-ec2353baa95b.png)
1.이 중 Linux, Window 폴더의 경우project 루트 디렉토리에 해당하는게 맞는지 궁금합니다. 
2.만약 그렇다면 아래 그림처럼 Dataset 폴더에 저장되어 있던 csv 파일과 images 폴더를 Linux나 Window와 같은 프로젝트 루트 디렉토리로 위치를 옮겨준 뒤 프로그램을 구현하는 것이 맞는 건가요?
![image](https://user-images.githubusercontent.com/95967939/194596064-2022f93f-5ccf-45d5-9899-e85ab8e510c8.png)
긴 글 읽어주셔 감사합니다.

**Comment by Lukious** [comment]
질문이 모호하여 답변이 올바를지 모르나 우선, Linux 폴더 안의 파일이 들어가있는 폴더에 전부 넣어서 구현해 주시면 됩니다.

Window폴더안의 파일은 참고용 입니다. 제출용이 아닙니다. 따라서 해당 디렉토리는 없는것으로 생각하시면 됩니다.

리눅스 빌드를 진행해 보시면 Makefile이 해당 디렉토리 안의 .cpp 파일과 .h파일을 소스로 삼아 컴파일 하심을 확인 하실수 있습니다. 

따라서 제출할 폴더 안에 이러한 소스파일과 이미지파일을 합쳐 제출해 주시면되겠습니다.

**Comment by mouse0429** [comment]
안녕하세요 데이터구조설계 수강 중인 2019202030학번 김민지입니다.
이미지 파일 위치 관련하여 추가 질문드릴 것이 있어 이슈를 다시 오픈하게 되었습니다

제안서의 제출방법을 보면
"확장자가 .cpp, .h, .pdf 가 아닌 파일은 제출하지 않음"
이라고 되어있습니다. 

저는 해당 부분을 Makefile, csv, 이미지 파일을 제외하고 소스코드만 제출하라는 의미로 해석했는데 해당 이슈에 이미지 파일을 함께 제출해도 된다고 답변을 주신 것을 보게되었습니다.

따라서 질문은 다음과 같습니다.
1. RAW 파일은 포함해서 제출해야 하나요?
2. 파일 경로는 자유롭게 설정해도 괜찮은가요? 
   현재 저의 경우 csv 에 imgDir 이 있던 점을 고려해
   `./img_files/~.RAW`, 로 제공해주신 Dataset을 넣은 상황입니다.

**Comment by 283kr** [comment]
> 질문이 모호하여 답변이 올바를지 모르나 우선, Linux 폴더 안의 파일이 들어가있는 폴더에 전부 넣어서 구현해 주시면 됩니다.
> 
> Window폴더안의 파일은 참고용 입니다. 제출용이 아닙니다. 따라서 해당 디렉토리는 없는것으로 생각하시면 됩니다.
> 
> 리눅스 빌드를 진행해 보시면 Makefile이 해당 디렉토리 안의 .cpp 파일과 .h파일을 소스로 삼아 컴파일 하심을 확인 하실수 있습니다.
> 
> 따라서 제출할 폴더 안에 이러한 소스파일과 이미지파일을 합쳐 제출해 주시면되겠습니다.

![image](https://user-images.githubusercontent.com/96465588/195530517-58d646ed-cbe9-40bd-8f6e-82214d938bad.png)

안녕하십니까. 데이터구조실습(금), 설계를 수강중인 2019610005 이방산입니다.

제출할 폴더 안에 소스파일이나 이미지 파일을 합쳐서 내야하는 것인지 궁금합니다.
현재 .cpp .h .pdf 파일 외에 다른 파일은 압축하지 않았으며 img edit 결과 따위는 report에 작성한 상태입니다.

**Comment by Lukious** [comment]
경로가 일반적이지 않은경우에는 함께 제출해주시면 되겠습니다.

확장자가 다른 파일도 제출하셔도 무방하며 제출시 감점은 없는것으로 하겠습니다.

다만 파일 용량이 초과할 수 있으니 모든 파일을 넣기보다 '이 경로에 파일을 넣으면 된다' 만 알 수 있게 제출해 주시면 되겠습니다.
