### ISSUE TITLE
Makefile 사용 관련 질문

### ISSUE THREAD

**Issue by 283kr** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#22]
안녕하십니까. 데이터구조실습(금), 설계를 수강중인 2019610005 이방산입니다.
프로젝트 스펙 pdf에 써있는 Makefile 관련 질문입니다.

![image](https://user-images.githubusercontent.com/96465588/194847809-f94a7197-eade-4a14-b331-1f9fae4dff92.png)

![image](https://user-images.githubusercontent.com/96465588/194847673-0124768f-a443-4ec1-a0fb-6a7320fa5a2c.png)

1. 
Makefile을 어떻게 사용해야 하는지 궁금합니다.
g++ -o run ds_project_main.cpp 명령어를 통해 run 파일을 만들었고
터미널에 ./run 을 입력하면 run 파일이 실행되는 것 까지는 확인했습니다.
그런데 Makefile을 어떻게 사용해야하는지, 어떻게 테스트 하는 것인지 잘 모르겠습니다.

어떻게 하라고 실습시간에 설명해주셨던 것 같은데 헷갈립니다. 감사합니다.

**Comment by ljiwoon** [comment]
안녕하세요, 데이터구조설계(월수)/실습(수) 수강 중인 이지운이라고 합니다.
```bash
make
````
해당 명령어만 입력하시면 output으로 run 파일이 나오는 것을 확인하실 수 있습니다.
감사합니다.

**Comment by 283kr** [comment]
> 안녕하세요, 데이터구조설계(월수)/실습(수) 수강 중인 이지운이라고 합니다.
> 
> ```shell
> make
> ```
> 
> 해당 명령어만 입력하시면 output으로 run 파일이 나오는 것을 확인하실 수 있습니다. 감사합니다.

make 파일이 실행파일인 run을 만드는거죠? 
와 감사합니다.
