### ISSUE TITLE
edit 경로설정 관련 질문

### ISSUE THREAD

**Issue by songyuri** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#23]
조교님 안녕하세요 2021202023 송유리입니다.
.raw파일이 images 폴더에 담겨있는데 경로설정이 안되는 상황입니다.
 
![image](https://user-images.githubusercontent.com/69284463/194980529-0e137115-bf04-40d4-b080-d8bc70e488c0.png)

./images/~~~.csv
./main/images/~~~.csv
\\main\\images\\~~~.csv 등 다 해봤는데 파일을 열지 못합니다.

그래서 그냥 main파일에 raw파일을 다 넣어서 하니까 실행이 되는데 꼭 .raw파일을 images 폴더에 담아야 하는지 궁금합니다.
감사합니다.

**Comment by mouse0429** [comment]
안녕하세요 데이터구조설계 수강 중인 2019202030학번 김민지입니다.
이미지 파일 위치 관련하여 추가 질문드릴 것이 있어 커멘트 남기게 되었습니다.
(참고 #21 )

제안서의 제출방법을 보면
"확장자가 .cpp, .h, .pdf 가 아닌 파일은 제출하지 않음"
이라고 되어있습니다.

저는 해당 부분을 Makefile, csv, 이미지 파일을 제외하고 소스코드만 제출하라는 의미로 해석했는데 해당 이슈(#21)에 이미지 파일을 함께 제출해도 된다고 답변을 주신 것을 보게되었습니다.

따라서 질문은 다음과 같습니다.

1. RAW 파일은 포함해서 제출해야 하나요?
2. 파일 경로는 자유롭게 설정해도 괜찮은가요?
현재 저의 경우 csv 에 imgDir 이 있던 점을 고려해
`./img_files/~.RAW` 로 제공해주신 Dataset을 넣은 상황입니다.

**Comment by Lukious** [comment]
@songyuri 
네 이미지 파일은 반드시 다른 폴더에 담겨있어야 합니다. (이미지/(선택적)csv파일만으로 존재하는)

@mouse0429 
이미지 파일만(혹은 csv와 함께) 담겨있는 폴더가 별도로 있다면 경로는 자유롭게 설정해도 괜찮습니다.
RAW파일의 제출을 요청 드리는 이유는 이미지가 어느 위치에 있을 때 정상 동작하는지 확인하기 위함입니다. (코드 평가를 위한)
해당 사항 참고하시어 제출해 주시면 되겠습니다.
