### ISSUE TITLE
보고서 Result Screen 관련

### ISSUE THREAD

**Issue by lmmh202** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#24]
안녕하세요 데이터구조실습(월)을 수강하고 있는 2021202071 이민형입니다.
현재 Linux환경 VScode에서 코딩을 하고 있는데, 결과화면을 캡처하고 동작을 설명할때
꼭 VMware의 Ubuntu환경에서 결과화면을 캡처해야하는지 궁금합니다.

감사합니다.

**Comment by Lukious** [comment]
다른 환경에서 캡쳐하여도 상관 없지만 리눅스에서 동작하는것을 반드시 확인해 주시기 바랍니다.
