### ISSUE TITLE
csv파일의 인코딩 UTF-8 BOM 관련 질문

### ISSUE THREAD

**Issue by 283kr** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#25]
안녕하십니까. 데이터구조실습(금), 설계를 수강중인 2019610005 이방산입니다.
프로젝트 csv파일의 인코딩에 대해 질문 있습니다.

1. 
프로젝트 테스트를 하며 csv파일 저장 인코딩이 UTF-8(BOM)으로 진행 된다고 생각해야 합니까?

2.
현재 UTF-8 저장 되었다고 생각하고 코드를 짰는데 UTF-8(BOM)으로 받아오면 오류가 납니다.
파일을 읽어올 때 UTF-8(BOM)을 UTF-8로 바꾸는 방법이 있는지 궁금합니다.

**Comment by Lukious** [comment]
1. 네 그렇습니다. 다만 파일 헤더 오류로 csv파일이 읽히지 않는 오류일 경우 채점 이후 방문하여 다른 헤더로 인코딩된 파일로 정상 동작하는 것을 보여주시면 본래 점수를 받으실 수 있도록 하겠습니다.

2. read하는 방식을 바꾸어 보시면 충분히 구현 하실 수 있을 것 입니다.

**Comment by 283kr** [comment]
네 감사합니다!

**Comment by 2h1082** [comment]
@Lukious 조교님 되물어 보는 것 같아 죄송합니다만, BOM처리에 애를 먹고 있어 여쭙니다. 1번 질의에 대한 답에 따르면, BOM으로 저장된 csv파일이 아니라 utf-8형식으로 바꾸어 다시 저장한 csv에서 작동한다면 감점이 없다는 뜻이실까요?
