### ISSUE TITLE
파일 대소문자 관련 질문사항

### ISSUE THREAD

**Issue by songyuri** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#26]
조교님 안녕하세요 2021202023 송유리입니다.
pdf 11쪽에 보면 출력은 "출력 포맷"을 따르라고 명시되어 있어서 출력예시와 똑같이 출력될 수 있도록 모든 명령어와 문장들을 대문자로 저장을 했고, edit을 통해 새로 만든 파일을 저장할 때는 소문자로 바꿔서 저장을 해줬습니다.
그런데 raw 파일 중에 대소문자가 섞여있는 파일의 경우 인식을 할 수가 없어서 불러오지를 못하는데 이것도 감점요소가 되는지 궁금하여 질문 남깁니다.
![image](https://user-images.githubusercontent.com/69284463/195145355-4349ddee-2f68-4cf3-9af8-8ff689595a9b.png)

**Comment by Lukious** [comment]
대소문자 구분은 필수적 입니다. 명령어의 대소문자 구분은 없으나, file을 read하는데 있어 대소문자가 영향을 미치는 경우는 코드가 하드코딩 되어 있을 때는 제외하고는 문제가 없다고 판단하며, 정상적인 구현이 아님으로 일반적인 동작을 위해 대소문자가 구분없이 파일이 read되어야 합니다. 

파일 이름에 대소문자가 있는 경우와 명령어가 대문자로 입력 될 수 있는 것은 별개의 구현입니다. (기능적으로 다르게 동작하는 코드 블록)

**Comment by SOM916** [comment]
@Lukious 그럼 파일 이름 같은 경우 대문자로 바꾸지 않아도 되는 건가요?
예시로 "The woman is looking at the man"같은 경우 노드에서는 "The woman is looking at the man" 으로 저장하지만 명령어 LOAD에서 결과를 출력해야 할 때 "THE WOMAN IS LOOKING AT THE MAN" 으로 출력해야 하는지 묻고 싶습니다. 제시한 pdf에서는 리스트 예시 사진을 보면  노드에서 파일이름 그대로를 대소문자를 섞어서 저장하고 있지만 출력 포맷 예시를 보면 대문자로 출력이 되어있습니다. 또한 MODIFY의 입력 예시를 보면 파일 이름을 대문자로 받고 있는데 여기서도 꼭 대문자로만 받아야하는건지 궁금합니다. 
만약 파일이름 그대로 저장하는 것이라면 명령어 SEARCH에서 단어를 찾을 때 "CUP"을 입력해도 "cup"을 찾을 수 있게 구현해야할까요? 아니면 대소문자를 구분해서 출력해야 할까요?
