### ISSUE TITLE
이미지 파일 관련 질문

### ISSUE THREAD

**Issue by bbbjihan** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#27]
안녕하세요, 데이터구조설계수업을 수강 중인 2020803077 박지한이라고 합니다.

본 프로젝트 제안서에서 다음 내용에 대한 해답을 찾지 못하여 질문 드립니다.

프로젝트 레포지토리에서 command.txt에 ADD 명령어의 인자로 작성되어 있는 new_filesnumbers.csv파일을 제공해주지 않으므로, 임의로 작성한 csv파일을 통해 ADD 명령어를 테스트해야 한다고 알고 있습니다.
만약 SELECT 명령어를 통해 선택된 Databse_BST_Node가 ADD 명령어를 통해 추가된 새로운 Node이며, 해당 Node의 DirectoryName / FileName으로 이미지파일을 불러올 수 없을 경우 어떻게 처리해야 하는지 궁금합니다.
Requirements in implementation에서 "읽어야할 파일이 존재하지 않을 경우 해당 파일을 생성한 뒤 진행하도록 한다."라 되어있는데 이에 해당하는 것인가요, 아니면 ADD 명령어로 추가되는 모든 Node에 대응하는 이미지파일이 존재한다는 가정을 하고 구현하여야 하는 것인가요?

**Comment by Lukious** [comment]
1. 이미지 파일을 불러 올 수 없는 경우는 테스트 하지 않습니다. 
2.  "읽어야할 파일이 존재하지 않을 경우 해당 파일을 생성한 뒤 진행하도록 한다." 해당 이슈는 이미 보고된 바 있으니 이슈 체크 부탁드립니다.
