### ISSUE TITLE
csv file 및 raw file의 경로에 대한 질문

### ISSUE THREAD

**Issue by dain0127** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#28]
안녕하세요 객프실 금요일 수업을 듣는 2020202007 백창인입니다.
1. LOAD나 ADD같은 명령어는 특정 디렉토리에서 이미지 file name과 고유 번호를 저장한 csv 파일을 읽어서, Linked list에 저장하는 기능의 명령어입니다.
하지만 과제 파일을 읽으면서 몇가지 가능성에 혼동이 와서 질문을 드립니다.

1 - (1)
https://github.com/Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1/issues/10#issue-1390141985
다른 csv파일 관련 issue를 참고해 보았을 때, 프로젝트의 root 디렉토리에 존재하는 csv file을 읽으라고 되어 있습니다. 이 경우 LOAD같은 경우에는 굳이 img_files 디렉토리의 filenumbers.csv 파일에서 읽는 것이 아니라, 그냥 img_files.csv 현재 디렉토리에서 읽는 것으로 생각하면 되는지 궁금합니다.

1 - (2)  
![image](https://user-images.githubusercontent.com/55676675/193472885-493049c2-6cf0-4afc-9eef-da70dffa1c3e.png)
위 사진 처럼 LOAD 명령어를 구현할 때에는 img_files 디렉토리에 있는 img_files.csv를 읽도록 되어있습니다. 이 경우, 아래 사진과 같이 소스 파일과 헤더 파일이 저장되어 있는, 디렉토리에 img_files/ img_files.csv를 찾도록 해야하는지 궁금합니다.
![image](https://user-images.githubusercontent.com/84649770/195207808-af3b2ef7-dd75-4275-8aca-b33f5402208a.png)

1 - (3)
github의 문서들을 보면, dataset 디렉토리에  img_files.csv가 있습니다. window 폴더는 참고용이라 뺀다고 쳐도, Linux폴더는 소스 파일이 담긴 프로젝트 폴더가 되고, Dataset에는 raw파일이 담겨있는 image 폴더와 img_files.csv가 담긴 폴더가 됩니다. github에 있는 파일들로 git clone을 해도 그대로 실행이 되려면 dataset에 있는 csv파일을 찾도록 경로를 설정해서  img_files.csv 읽어야하는지 모르겠습니다.

ADD또한 마찬가지입니다. 소스파일이 함께 있는 폴더에 csv이있다고 해야하는지, 아니면 그곳에 new_file/ 라는 디렉토리같은 것을 찾아서 읽어야하는지, 아니면 dataset에 있다고 치고 csv파일을 읽어야하는지 모르겠습니다.

2.  raw 파일은 정확히 어느 곳에 존재한다고 생각하면 되는지 모르겠습니다.

2-(1)
LOAD 명령어같은 경우에는  img_files 디렉토리에 존재하는 img_files.csv를 읽습니다. 이후에 select 명령에서 고유 번호를 통해 찾은 dir/file/number 이미지 데이터를 이용해 어느 곳에 존재하는 raw 파일을 edit합니다.
이때 raw 파일은 img_files 같은 디렉토리 따위에 있는지 궁금합니다. 즉, csv 파일과 같은 디렉토리에 있는 것으로 간주하면 되는지 궁금합니다.
만약 이게 아니라면, img_files 디렉토리는  img_files.csv 파일한 하나 덩그러니 있는 것인지 궁금합니다.

2-(2)
1-(3) 과 마찬가지로 github에는 dataset/images/ 폴더에 raw파일이 존재합니다.  여러 기타 csv파일 에 해당되는 이미지들은 모두  dataset/image/ 폴더에 모여 있다고 생각하고 과제를 진행해야하는지 모르겠습니다.

제시한 스켈레톤 코드의 window/rawreader.cpp같은 경우에는 input_file = fopen("./images/couple.raw", "rb");와 같은 방식으로 경로를 설정했습니다. 이 경우는 ADD 명령어로 images 디렉토리의 Linked list를 수행한 이후 images 디렉토리가 존재한다고 가정하고 구현을 한 것인지, 아니면 dataset/images/ 인지 궁금합니다.

만약 dataset/images가 아니라면 dataset 폴더는 그저 참고나 테스트용으로 존재하는 것이 맞는지 궁금합니다.

**Comment by Lukious** [comment]
1. #10 에서 보고한것과 같이 csv파일의 위치는 선택입니다. ADD LOAD모두 동일하게 첫번째 기본 csv파일을 읽을 수 있는 위치를 설정해두신뒤 프로젝트 파일로 제출하시면 해당 경로를 참고삼아 테스트 하여 평가도록 하겠습니다. 디렉토리의 위치가 평가에 미치는 영향은 없습니다. (목적으로 하는 파일들만 잘 구분되어 있다면 eg,이미지파일과 csv파일이 들어가 있는 폴더만 잘 정의되어 있다면 경로 이름이나 위치는 평가에 반영 되지 않음)

2. 마찬가지 입니다 보고서 및 주석에서 위치와 작동 방식만 잘 작성해 주시면 됩니다.

본 수업 및 프로젝트의 취지는 학생이 자료구조를 설계하여보고 알고리즘을 통해 자료구조를 다루는 방식에 대해 이해하는 수업입니다. 파일의 디렉토리의 위치는 구현에 있어 핵심적인 사항이 아님으로 해당 부분에서 문제가 발생해도 코드가 자체가 돌아가지 않을 수준이 아니면 감정사항이 아니니 크게 걱정마시고 알고리즘 및 자료구조 활용 위주의 구현에 포커싱하여 과제 진행해 주신뒤 제출해 주시면 됩니다.

감사합니다.
