### ISSUE TITLE
에러 출력 방법 관련 질문

### ISSUE THREAD

**Issue by bbbjihan** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#29]
안녕하세요, 데이터구조설계 수강중인 2020803077 박지한입니다.

출력 방법과 관련하여 확인받고자 하는 점들이 있어서 질문 남깁니다.
제안서와 해당 레포지토리의 이슈란, 조교님께서 말씀하신 내용들을 종합해보자면
1. 콘솔 출력은 채점에 영향을 주지 않는다.
2. 출력 경로는 `/log.txt`이다.

인 건가요? 그렇다면 스켈레톤 코드에 작성되어 있는 `ferr`는 작성하지 않아도 되는 것인가요?

=> 예를 들어 LOAD를 수행한 뒤 ADD 명령어에서 에러가 발생한다면,

 `/log.txt`

> ======ADD======
~~
===============
=====ERROR=====
200
===============

이런 식으로 log.txt 파일에 출력하도록 구현하면 되나요?

또한, 예외처리를 result 클래스를 통해 실시하지 않아도 괜찮을까요?

**Comment by Lukious** [comment]
1. 네 맞습니다 에러로그를 txt파일에 출력해 주시면됩니다.
2. 네 스켈레톤 코드는 자유롭게 수정 가능함으로 꼭 해당 클래스에 구현해야 하는것이 아닙니다.
