### ISSUE TITLE
STL 사용 관련 문의

### ISSUE THREAD

**Issue by hamoci** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#3]
안녕하세요. 데이터구조설계 및 실습(수)을 수강중인 컴퓨터정보공학부 하준혁입니다.

실제로 구현하도록 명시된 Loaded_LIST나 BST, Queue, Stack의 구현에 vector STL을 사용하는 것이 아니고, 
filesnumbers.csv 파일을 읽어 여기에 있는 text를 임시로 vector STL에 저장하고 싶은데 혹시 가능할까요?

감사합니다.

**Comment by Lukious** [comment]
네 상관 없습니다.

감사합니다.
