### ISSUE TITLE
load 시 발생하는 오류

### ISSUE THREAD

**Issue by H4nnhoi** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#30]
안녕하세요 데이터구조설계수업을 듣고 있는 2020202047_이정한입니다.

윈도우로 코드를 작성하고 리눅스에서 옮기는 작업중 생긴 문제에 대해 질무드립니다.
![load_error_cp](https://user-images.githubusercontent.com/69452755/195479884-89385399-4a1a-4112-a348-637b6ef15129.PNG)
위 사진과 같이 load 함수에서 경로를 설정하고 파일을 오픈한다면 작업을 진행할 수 있게 했으며 만약 pFile이 null이 나온다면 error를 출력하도록 했습니다. 같은 작업을 윈도우에서 실행했을 때는 제대로 작동했지만 리눅스에서는 에러코드를 출력합니다.  어떤 문제 때문에 파일 열람이 안되는지 알고싶습니다.

(디렉토리의 위치들과 이름은 윈도우와 동일합니다.)

**Comment by Lukious** [comment]
현재 학생이 전달해 주신 자료만으로는 어떤 부분이 문제인지 파악이 쉽지 않습니다.

에러상황/환경/메시지/구현 방법등을 모두 보고해 주시기 바랍니다.

더불어 에러상황이 일반적인 구현에 관한 질문이시라면 형평성을 위해 조교 배정이 불가함 또한 안내드립니다.

**Comment by 283kr** [comment]
> 안녕하세요 데이터구조설계수업을 듣고 있는 2020202047_이정한입니다.
> 
> 윈도우로 코드를 작성하고 리눅스에서 옮기는 작업중 생긴 문제에 대해 질무드립니다. ![load_error_cp](https://user-images.githubusercontent.com/69452755/195479884-89385399-4a1a-4112-a348-637b6ef15129.PNG) 위 사진과 같이 load 함수에서 경로를 설정하고 파일을 오픈한다면 작업을 진행할 수 있게 했으며 만약 pFile이 null이 나온다면 error를 출력하도록 했습니다. 같은 작업을 윈도우에서 실행했을 때는 제대로 작동했지만 리눅스에서는 에러코드를 출력합니다. 어떤 문제 때문에 파일 열람이 안되는지 알고싶습니다.
> 
> (디렉토리의 위치들과 이름은 윈도우와 동일합니다.)

저도 비슷한 문제를 경험해서 혹시 이 문제가 아닐까 하고 적어보겠습니다.

1. 리눅스에서 상대 경로 써줄 때 \\가 아니라 그냥 /만 써야 작동했습니다.
위에 경로로 따지면 ./img_files/filesnumber.csv로 해보시겠습니까?

2. 제가 겪은 또다른 문제는 리눅스에서 파일을 읽어올 때 getline으로 읽어오면 개행문자가 같이 포함 돼 읽어졌습니다. 윈도우에선 그러지 않았습니다. 그래서 str.pop_back()로 string 마지막 개행문자를 빼주었습니다.

혹시 이런 문제 아닐까 싶습니다.
