### ISSUE TITLE
csv 파일 인코딩 방식

### ISSUE THREAD

**Issue by gitSoyoungLee** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#31]
![image](https://user-images.githubusercontent.com/72489644/195492246-52d89bf5-184e-4e8c-b0d8-695d955f83c5.png)

안녕하세요 
실습 (금) 분반 듣는 2021202039 이소영입니다.

이방산 학우 분의 질문과 그에 대한 조교님의 답변(https://github.com/Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1/issues/25)을 보고 헷갈려서 질문합니다.

채점 시 UTF-8(BOM)으로 인코딩된 csv파일을 기준으로 하지만
만약 오류 시 방문하여 문의하면 ANSI나 UTF-8로 인코딩된 csv파일도 테스트 가능하고 따로 감점은 없다는 뜻으로 이해했는데
제가 맞게 이해한건지 확신이 안 들어서 글을 올립니다.

감사합니다.

**Comment by Lukious** [comment]
네 맞게 이해하셨습니다.
