### ISSUE TITLE
추가제출 기한 제출

### ISSUE THREAD

**Issue by joon0723** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#32]
안녕하세요, 현재 데이터구조설계 수업을 수강하고 있는 2021202054 송예준입니다. 다름이 아니라 klas 과제추가제출 기한이 10월 14일 오전 12시부터 12시 59분 59초라 나와있는데 이때 제출했으면 감점되나요?

**Comment by Lukious** [comment]
네 제출 마감일 익일 제출시(14일 제출 시간에 제출시) 제안서 내용대로 감점있는점 확인드립니다.
