### ISSUE TITLE
csv파일 오픈 중 오류질문

### ISSUE THREAD

**Issue by Nexgeyoon** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#4]
안녕하세요 데이터구조실습(금)을 수강 중인 컴퓨터정보공학부 윤종협입니다.
csv파일을 읽는 예제코드를 따라서 연습하던 중에 오류가 발생하여 질문드립니다.
![8899](https://user-images.githubusercontent.com/113813993/191453894-0f5a886c-66c7-4d8d-bd5f-1a365c6a7a92.jpg)
위 결과화면과 같이 첫 정보를 입력받아 고유번호와 파일명을 분리하는 중에 오류가 발생하였고, 마지막 정보는 두 번 입력되었으며 두번째는 오류가 발생하여 입력되었습니다.
![889](https://user-images.githubusercontent.com/113813993/191454875-5182713e-6924-49ee-aa57-9ffc56a766d4.jpg)
이에 고유번호와 파일명을 분리하기 전에 csv 파일에서 읽어온 정보를 출력하여 검사하였더니 정보를 파일에서 받아오는 과정에서 오류가 발생함을 확인할 수 있었습니다.
이런 오류가 발생하는 원인이 무엇인가요? 또한 마지막 정보가 두 번 입력되는 이유는 무엇인가요?

또한 예제에서 int argc, char*argv[]가 main함수가 선언될 때 ()에 들어가 있는 이유와 코드에서 하는 역할, 깃허브 issue탭에 코드를 첨부하는 방법도 알려주시면 감사하겠습니다.

**Comment by hamoci** [comment]
안녕하세요. 데이터구조실습(수)을 듣는 컴퓨터정보공학부 하준혁이라고 합니다. 시간이 꽤 지났는데 답이 달리지 않아 이렇게 작성해봅니다. 제가 조교님은 아니지만, 어느 정도 답을 드릴 수 있을 것같아 답변 드립니다.
### (1) int argc, char* argv[]를 사용하는 이유에 대해서
File을 open하는 프로그램을 작성할 때 하나의 문제에 직면하게 됩니다. 프로그램에 어떻게 File의 이름을 전달할지입니다. File의 이름을 프로그램 안에 넣어 빌드하는 것은 프로그램의 flexibility를 저하시킵니다. 여기에 대한 좋은 해결책으로는 프로그램이 command-line을 통해 file의 이름을 얻는 것입니다.
이는 main 함수에 `int argc`, `char *argv[]` 라는 2개의 parameter를 정의하는 것으로 가능하게 됩니다.
```c
int main(int argc, char *argv[]) {
    //...
}
```
`argc`는 command-line으로 전달되는 arguments의 개수입니다.
`argv`는 argument strings를 가리키는 pointer의 배열입니다.
만약에 linux의 terminal에 다음과 같은 명령어로 demo 라는 이름의 프로그램을 실행해본다고 생각해보면 좋을 것 같습니다.
```
demo names.dat dates.dat
```
이러한 상황에서 `argc`는 전달된 argument의 개수인 3을 값으로 가지게 됩니다. `argv[0]`은 program의 이름인 `demo` 가리키게 됩니다. `argv[1]`부터 `argv[argc-1]`까지는 각각 남은 arguments를 가리키게 됩니다. 위의 예시에서는 `argv[1]`이 `names.dat`, `argv[2]`가 `dates.dat`을 가리키게 됩니다. 그리고 `argv[argc]`는 null pointer를 가집니다.
정리하자면, `int argc`와 `char* argv[]`는 program의 시작과 동시에 main 함수에 전달해야 할 argument가 필요할 때 사용하게 됩니다. 위의 예시에서는 file의 이름을 전달하였죠. 하지만 이는 비단 file의 이름을 전달하는 것에 그치지 않고,   Linux Terminal 명령어인 `ls -a`와 같이 `-a`라는 argument를 전달하는 것처럼 사용할 수 있습니다.

위의 답변은  C Programming : A Modern Approach, 2/E /K.N.K King을 참고하였습니다.

### (2) 코드를 첨부하는 법에 대해
코드를 첨부하는 것은 다양한 방법이 있지만, 자신이 현재 작성중인 코드를 복사 붙여넣기 하기 위해 가장 쉬운 방법은 \' 를 사용하는 것입니다. 이 문자는 esc 아래에 있고, tab의 위에 있으며 숫자 1의 왼쪽에 위치한 키입니다. 이를 3개 연달아 입력하고 그 바로 다음 사용할 언어를 쓴다음 (ex. cpp) 코드를 작성하고 다시 \`를 3개 연달아 입력해주시면 됩니다.
\`\`\`cpp
code
\`\`\`


### (3) `%S` conversion specification에 대해
`%s`와 `%S`는 다릅니다. 아래의 링크를 참조하시면 더 확실한 정보를 얻으실 수 있습니다.

https://learn.microsoft.com/ko-kr/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170

`%s`의 경우에는 `char *` 자료형을 요구하고, `%S`의 경우는 `wchar_t *` 자료형을 요구하는데요, 우리의 실습 환경에서는 `char`의 경우에는 1byte, `wchar_t`의 경우 2byte를 요구합니다. 
왜 이러한 일이 일어났을까요? 이는 locale 문제가 있기 때문입니다. ASCII character set은 널리 사용되고 많이 알려져있는데요, 이 세상에 있는 모든 문자가 ASCII로 표현할 수 있는 것은 아닙니다. 그렇기 때문에 특히 아시아권 나라에서는 아주 큰 character set을 필요로 했습니다. 이를 표현하는 방법으로 연속된 1개 또는 2개의 bytes로 표현되는 확장된 character인 `Multibyte character`를 사용하기도 하였습니다. 
또다른 방법으로는 `wide character`로 문자를 표현하는 것입니다. 길이가 다를 수 있는 multibyte character와는 다르게 모든 wide character는 특정한 구현을 통해 동일한 bytes를 가져야하도록 하였습니다. 저도 여기에 대해서 막 자세하게 아는 것은 아니라서 관심있으시면 좀더 찾아보시면 많은 정보를 얻을 수 있으실겁니다.
결론적으로, `char`와  `wchar_t`가 나타내는 byte가 다르기 때문에 printf로 출력이 안되었을 가능성이 높습니다. `%S`를 `%s`로 바꾸면 문제가 해결될 것이라고 생각됩니다.

위의 답변은  C Programming : A Modern Approach, 2/E /K.N.K King을 참고하였습니다.

### (4) 첫번째 사진의 마지막에 정보가 두 번 입력되는 이유
먼저 아주 좋은 글을 발견하여 링크를 첨부합니다.
https://stackoverflow.com/questions/5431941/why-is-while-feoffile-always-wrong
위 사이트의 첫번째 답변도 아주 좋은 답변이지만, 두번째 답변이 아마 원하시는 해답일 것입니다.

윤종협님이 사용하신 filesnumbers.csv 파일은 아마 파일의 마지막에 개행문자가 들어가 있을 것입니다.
이 개행문자로 인해 2번 반복되는데, 이유는 `if`구문 이내의 `feof(pFile)`때문입니다.
fgets는 개행문자 (`\n`)까지 읽거나 정해진 글자 수만큼 읽고,  뒤에 `\0`을 붙여 문자열로 만든 뒤 buffer에 저장합니다(코드의 경우엔 `str_tmp`). filesnumbers.csv 파일의 마지막 줄인 `999,fence is near trees.RAW`까지 읽었다고 생각해봅시다. `999,fence is near trees.RAW`의 마지막 부분인 `\n` 뒤가 파일의 끝인가요? 아닙니다. \n 다음줄이 EOF이죠. 그렇기 때문에 `999,fence is near trees.RAW`를 읽은 이후 `if`구문의 조건인 `EOF`을 만나지 않았으면 이라는 조건을 만족하여 구문이 한번더 실행하게 됩니다. 이렇게 되면 EOF를 읽게 되고 그제서야 루프를 탈출하게 됩니다.

아래부터는 저의 추측입니다.(정답이 아닐 수있으니 참고만 하세요)
`999,fence is near trees.RAW`를 출력하였을 때 변수 str_tmp에 들어있는 값은 "fence is near trees.RAW\n"일 것입니다. 그리고 출력 이후에 다시 한번 `fgets` 함수가 호출될 것이고, 당연히 파일의 끝을 읽어들였고 아무 값도 읽어들이지 못했기 때문에 `str_tmp`의 값은 변하지 않았을 것이고 이 상태로 `while(str_tmp[temp + 1] != NULL`의 검사식을 거치게 됩니다. 이 검사식을 거치고 문자열이 다시 한번 가공될 것이고, 당연히 원하는 결과가 출력되지 않을것입니다. 
 마지막 숫자는 왜 5992가 나왔을까요? 생각해보면 간단합니다. str_tmp에 들어있는 값이 "fence is near tress.RAW\n"이기 때문에 아스키코드를 분석해보면,
str_tmp[0] 은 'f' = 102
str_tmp[1] 은 'e' = 101
str_tmp[2] 는 'n' = 110
102 - '0' = 102 - 48 = 54
101 - '0' = 101 - 48 = 53
110 - '0' = 110 - 48 = 62

54 * 100 + 53 * 10 + 62 = 5400 + 530 + 62 = 5992

따라서 num에 저장된 숫자는 5992입니다. 

`feof(pFile)`의 조건식을 사용할 뿐만 아니라 잘못된 문자열을 읽어들였을 때의 예외처리또한 해주어야 프로그램이 올바르게 동작할 것입니다.

### (5) 두번째 사진의 쓰레기값 출력
(3)에서 말씀드린 `wchar_t`의 문제일 것이라고 생각되는데, 잘 모르겠습니다.
감사합니다.

**Comment by Nexgeyoon** [comment]
답변 감사합니다. 하지만 답변에도 불구하고 여전히 첫 정보를  load할 때 잘못된 정보를 load하는 현상은 계속 일어나는 것이 확인되었습니다.
![9999](https://user-images.githubusercontent.com/113813993/191877523-26ae4e16-c4a9-4fa0-a2ea-647c4d5ef0fd.jpg)

**Comment by Lukious** [comment]
감사합니다 하준혁 학생, 문제에 대한 분석이나 조사, 레퍼런스 정리와 해결책 구안 등 정말 좋은 답변이였습니다. 고생많으셨습니다.

윤종협 학생의 질문의 경우 질문의 모호성과 프로젝트 범위를 벗어난 질문, 평가요소에 해당되는 기능에 대한 질문 등이 있었기 때문에 실습시간에 질문을 전체 코드를 보며 정리해 주기위해 답변이 늦었습니다. 금일 실습 시간에 문제 파악을 도와드리겠습니다.

그 전에 질문을 하는데 도움이 될 팁을 공유 드리고자 합니다.

<h2> 문제 검색</h2> 
윤종협 학생의 첫번째 질문은 두가지 이유로 반려되었습니다. 첫번째는 프로그램 기능구현의 핵심적 요소인것과(공정한 평가를 위해 반려) 두번째로 부족한 사전 해결노력 대한 설명입니다. 본 과제의 프로그램을 작성하는 이유는 과목의 이름대로 자료구조의 특성을 학습하고자 하는 바도 있지만 프로젝트 과목의 대 목표인 앞으로 프로그램을 구현하는데 있어 마주칠 다양한 문제들을 어떻게 접근하여 해결 하는지에 있습니다. 이러한 문제들을 탐색하기 위해 문제를 정의할 적절한 키워드를 고르고 검색하여 같은 문제에 대해 보고된 내용을 레퍼런스 하여 문제를 해결하는 능력은 개발자로서 필수적인 요소라고 생각합니다. 

윤종협 학생의 질문을 분석해 보겠습니다.

**문제상황 : csv 파일을 읽는데 있어 마지막 라인이 두번 읽힌다.**

해당 문제를 그대로 구글에 검색해 보겠습니다.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/25575989/191880840-ffb8a1e0-91e6-4ad5-b9a3-3327132fa135.png">

해당 글에서는 이렇게 설명하고 있습니다.

<img width="1026" alt="스크린샷 2022-09-23 오전 11 16 00" src="https://user-images.githubusercontent.com/25575989/191881437-493d9f0b-87b8-48f8-b51d-b3dc0277161c.png">

해당글의 레퍼런스에서는 보다 정확한 내용을 확인 할 수 있습니다.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/25575989/191880926-93419d8c-e630-4e32-b41f-dc897f307dc2.png">

두번째 문제상황을 영문으로 검색하고 사용한 함수인 fgets를 추가하면 보다 더 정확한 레퍼런스를 많이 찾을 수 있습니다.

<img width="844" alt="스크린샷 2022-09-23 오전 11 19 04" src="https://user-images.githubusercontent.com/25575989/191881110-a988a7be-cac4-464a-9a60-073a601f8183.png">

이러한 방식으로 답을 찾아나가면, 간단한 문제들은 쉽게 해결할 수 있을것 입니다.

특히 학생의 두번째 세번째 질문 또한 간단한 검색을 통해 코드 첨부 방법, main인자의 역할을 알아 볼 수 있었을 것 입니다.


<h2> 코드 질문의 요령 </h2> 
작성한 코드에 대해 질문 할 때에는 스스로 코드에 대한 이해와 코드를 이해 하는 사람을 위한 설명이 필요합니다. 이것이 주석이 필요한 이유이며 차후 문제 해결에 대한 설명을 스스로 이해하기 위해서라도 반드시 필요한 작업입니다.

윤종협 학생의 코드의 경우 주석이 없고 코드에 대한 설명도 부족해 문제를 파악하는데 너무 많은 시간이 걸립니다. 빠른 답변과 적절한 이해 정도 파악을 위해 설명의 디테일을 추가해 질문하면 다른 답변자들이 문제를 파악하는데 더욱 용이할 것 입니다.

**Comment by Nexgeyoon** [comment]
csv파일 load 시 첫 글자가 깨지는 원인은 csv파일이 인코딩이 UTF-8로 설정되어있기 때문이었습니다.
같은 현상이 일어나시는 분들은 csv파일을 메모장으로 연결하여 연 뒤 다른 이름으로 저장을 선택하여 인코딩 방식을 ANSI로 바꾸고 저장을 눌러주세요.

**Comment by Lukious** [comment]
문제가 해결 된 것 같음으로 close 하겠습니다.

**Comment by 283kr** [comment]
> csv파일 load 시 첫 글자가 깨지는 원인은 csv파일이 인코딩이 UTF-8로 설정되어있기 때문이었습니다. 같은 현상이 일어나시는 분들은 csv파일을 메모장으로 연결하여 연 뒤 다른 이름으로 저장을 선택하여 인코딩 방식을 ANSI로 바꾸고 저장을 눌러주세요.

인코딩을 바꾸는 이 부분은 저희가 임의로 바꿔도 되는 부분입니까? 아니면 이것까지 고려하여 코드를 구현해야 합니까?

**Comment by Lukious** [comment]
@283kr 가장 좋은 솔루션은 이것까지 고려하여 코드를 짜는 방식입니다. 

매우쉽게 코드에서 read 하는 형식을 설정할 수 있는 방법이 있습니다.

직접 찾아보시고 레퍼런스 하여 적용해 보신후 고찰에서 해당 인코딩의 다른점과 읽는 방식 등을 보고해보면 좋은 평가요소 일 것 같습니다.
