### ISSUE TITLE
고유번호(Unique Number)와 MOVE 명령어에 대한 질문

### ISSUE THREAD

**Issue by hamoci** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#5]
안녕하세요. 데이터구조실습(수), 설계를 수강중인 컴퓨터정보공학부 하준혁입니다.
구현 중, 궁금증이 생겨 문의 드립니다.

(1) MODIFY 명령어를 통해 고유번호를 수정 했을 시에, filesnumbers.csv 파일 내의 고유번호 또한 수정해야하나요?

(2) Image File 추가 시에 고유번호가 중복된다면 거기에 대한 처리를 어떻게 해야할까요?
예를 들어 고유번호 100을 가진 Node가 Loaded_LIST에 이미 존재하고, ADD 명령어를 통해 고유번호 100을 가진 Node를 추가하려고 한다면 이를 추가하지 않고 Skip을 해야하는지 아니면 Loaded_LIST내의 중복된 고유번호를 삭제하고 추가해야하는지 궁금합니다.

(3) MOVE 명령어를 사용하여 Database_BST에 집어넣을때 고유번호가 겹치는 상황이 발생할 가능성이 있을 것 같습니다. 고유번호가 같으면 BST의 형태를 유지시키기 위해서 이 데이터를 삽입하지 못하는데, 이 경우 데이터가 Loaded_LIST에 남아 있어야 하는지 궁금합니다.

(4)PDF를 보면, 11페이지의 Requirements in implementation 항목에 "읽어야할 파일이 존재하지 않을 경우 해당 파일을 생성한 뒤 진행하도록 한다"라고 쓰여있는데 LOAD나 ADD명령어의 상세를 보면 존재하지 않을 경우 ERROR Code를 발생시키도록 구현하라는 설명이 있습니다. ERROR Code를 발생시키고 csv 파일을 발견하지 못했을 경우 빈 csv 파일을 생성하는 것으로 이해하면 될까요?

긴 글 읽어주셔서 감사합니다.

**Comment by Lukious** [comment]
(1) 아닙니다. DB상의 숫자만 변경하면 됩니다

(2) 중복되는 경우는 없음을 가정합니다

(3) (2)와 마찬가지로 겹치는 경우가 없는 상황을 가정합니다

(4) 네 말씀해주신대로 구현하시면 됩니다.

**Comment by hamoci** [comment]
답변 감사드립니다.
