### ISSUE TITLE
명령어 입력 및 LOAD,ADD 명령어 관련 문의

### ISSUE THREAD

**Issue by leech1211** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#6]
안녕하세요. 데이터구조실습(수), 설계를 수강중인 컴퓨터정보공학부 이창훈입니다.
과제 진행중 헷갈리는 점이 있어 이슈를 남깁니다

1. 프로그램의 명령어를 입력받는 방법
- git clone을 받아 스켈레톤 코드를 참고하던 중 commend.txt 파일을 발견하였고 해당 파일안에는 LOAD라는 단어만 저장되어 있는것을 발견했습니다 LOAD 는 이번 과제의 명령어중 하나인데 그렇다면 이번과제의 명령어는 main함수 실행시에 사용자에게 입력을 받는것이 아닌 commend.txt 파일 내부에 저장되어있는 명령어 순서에 따라 실행되는 것인가요? 만약 그렇다면 ADD 나 MODIFY 처럼 명령어 뒤에 다른 키워드가 붙는 명령어들의 키워드도 commend.txt에 명시되어 있다고 가정하고 진행하면 되는 것인가요?

2. LOAD,ADD 명령어의 대한 질문
![image](https://user-images.githubusercontent.com/55794835/192219005-4b84faee-a14c-4ac8-9df4-b37a24220e83.png)
PDF에서는 이렇게 명시되어 있습니다 즉 새로추가되는 디렉토리들은 리스트를 통해 연결된다는 것으로 이해 했습니다 그럼 'image_files' 와 'new_files'는 리스트 형식으로 연결되는데 이때 리스트는 배열을 말하는 것인지 STL 의 list을 말하는 것인지 궁금합니다

감사합니다

**Comment by Lukious** [comment]
(1) command.txt를 바탕으로 명령을 입력받습니다. 관련내용 문서에 추가하여 금일중에 배포예정입니다

(2) 디렉토리명 노드간의 연결은 일반 List입니다. 파일노드간의 연결만 Linked-list구조입니다.

**Comment by mirusu400** [comment]
`일반 List`의 조건이 정확히 무엇인지 여쭤봐도 될까요? 이미 Linked List로 구현을 했는데 다시 배열을 이용한 리스트나 다른 리스트 구조로 구현이 필요한지 궁금합니다.
