### ISSUE TITLE
Loaded_LIST의 파일의 이름에 대한 질문과 최대 가질 수 있는 데이터에 대한 질문

### ISSUE THREAD

**Issue by 283kr** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#7]
안녕하십니까. 데이터구조실습(금), 설계를 수강중인 2019610005 이방산입니다.
문제 이해 중에  헷갈리는 것이 있어 질문 드립니다.

1. Loaded_LIST에 저장되는 파일의 이름은 .RAW를 빼고 넣어줘야 하는 것이 맞습니까? 현재 filesnumbers.csv 의 파일명에는 .RAW가 붙어 있습니다.

2. 
![image](https://user-images.githubusercontent.com/96465588/192297213-f4e07e8c-ea2b-4552-a910-7d118702ccc3.png)

과제 스펙 설명 pdf 3페이지의 한 부분입니다.

질문 드릴 것은 
(1) Loaded_LIST 자체가 100개 이상의 노드를 가질 수 없도록 구현 해야합니까?
(2) 아니면 MOVE 명령어 수행 시 100개를 맞춰서 트리에 넣어주면 되는 것입니까?

(1)의 경우라면 
![image](https://user-images.githubusercontent.com/96465588/192298104-0efd31ed-240a-4c82-aacf-1afaf579bab3.png)
위 사진과 같이 최대 개수가 5개라면 215노드가 들어온 시점에 가장 먼저 들어온 300이 빠지는게 맞습니까?
추가로 위 사진과 같다면 Loaded_LIST에서 노드 자체를 삭제해야하는지
MOVE 명령어 수행시 bst로 넘어가는 데이터만 100개 넘기면 되는지도 궁금합니다.

(2)의 경우라면
큐 따위를 이용하여 100개를 제한해 두고 100개가 넘는다면 먼저 들어온 데이터에 대한 노드를 삭제하며
큐의 꼬리 즉, 100번째가 bst의 root가 되는 것이 맞습니까?
즉,
![image](https://user-images.githubusercontent.com/96465588/192299709-b2b696d0-185a-4c74-a274-c43172a06593.png)
이 처럼 이해하는게 맞습니까?

(1), (2) 둘 중에 어떻게 생각해야 하는지 질문드립니다.

**Comment by Lukious** [comment]
(1) .raw를 빼고 넣어야합니다. csv파일의 string을 전처리 하시면 됩니다.

(2) 스펙에 작성된대로 데이터가 100개가 넘을 때 먼저 들어왔던 데이터에 대한 노드를 제거 후 새로운 데이터를 추가하시면 됩니다.

**Comment by 283kr** [comment]
답변 감사합니다!
