### ISSUE TITLE
스켈레톤 관련 문의

### ISSUE THREAD

**Issue by papercastl3** [Lukious/2022_Kwangwoon_Univ_CE_DS_Project_1#9]
안녕하세요. 데이터구조실습(월), 설계를 수강중인 컴퓨터정보공학부 한지성입니다.
구현 중, 궁금증이 생겨 문의 드립니다.
1.

![image](https://user-images.githubusercontent.com/92132704/192815426-bef74b0a-69f9-412b-8ffe-265a566167f0.png)

저는 위에 있는 코드(DS_Project1.cpp)가 main함수가 있기에 여기서부터 프로그램이 시작한다는 것으로 이해했습니다.
궁금한 점은 argv[1]에는 명령어를 실행하려면 실행할 파일의 이름을 알아야 하기 위해 
command.txt라는 값이 들어갈 것으로 생각했는데, 여기서 argv[2]는 atoi를 통하여 문자열을 int형으로 변환하는 것으로 보아 숫자의 입력 같은데, 명령어들은 command.txt안에 있는 내용을 읽어오기 때문에, main함수의 인자에 숫자가 들어올게 무엇인지 모르겠습니다.
![image](https://user-images.githubusercontent.com/92132704/192815172-e2797798-b05b-4147-a41d-cd1ceba3310b.png)
따라서 TreeManager.h을 보았지만, TreeManager의 생성자에는 인자가 1개 밖에 없어서 무엇이 맞는지 모르겠습니다.
![image](https://user-images.githubusercontent.com/92132704/192815885-14c72048-1028-414b-9b75-8130be8c3a0c.png)
따라서 다시 TreeManager.cpp에서 생성자를 다시 보았더니, 여기서는 unique_number라는 인자가 있어서 보았지만,  프로그램의 실행
흐름상 load명령어를 통하여 loaded_list를 만들어 이미지를 저장하는 것이 맞는 흐름 같아서 잘 이해가 안갑니다.
제 생각에는 이전의 스켈레톤 코드처럼 main함수에서  manager.run메소드를 통하여 시작하는 코드가 더 맞다고 생각하는데, 주석으로 to do implement가 되어있는 부분외에 있는 부분들을 임의로 인자와 내용을 바꾸어도 되는 지 궁금합니다.

2.
![image](https://user-images.githubusercontent.com/92132704/192820677-485b33bc-f47c-4001-ab71-39a710c247ad.png)
위 코드에서 fout은 manager.h에서 ofstream으로 정의되어 있지만, ferr은 없어서 임의로 하나를 더 만들어야 하는 지 궁금합니다.

**Comment by Lukious** [comment]
1과 2 모두 스켈레톤 코드를 자유롭게 편집하여 만드시면 됩니다.

스켈레톤 코드는 마음대로 수정하셔도, 혹은 아예 사용하지 않으셔도 무방합니다.
